export const services: Service[] = [
  {
    id: "1",
    category: "Skin",
    title: "Scarlet SRF: Revitalize Your Skin",
    subTitle: "Next-Gen Skin Tightening",
    imgUrl: "/img/scarlet-srf-min.jpeg",
    href: "/scarlet-srf",
  },
  {
    id: "2",
    category: "Skin",
    title: "Laser Resurfacing: Erase Imperfections",
    subTitle: "Precision Laser Therapy",
    imgUrl: "/img/laser-resurfacing-min.jpeg",
    href: "/laser-resurfacing",
  },
  {
    id: "3",
    category: "Skin",
    title: "HALO: The Future of Laser Treatments",
    subTitle: "Dual Wavelength Innovation",
    imgUrl: "/img/HALO-min.jpeg",
    href: "/halo",
  },
  {
    id: "4",
    category: "Skin",
    title: "BBL Forever Young: Banish Blemishes",
    subTitle: "Your New Skin Solution",
    imgUrl: "/img/bbl.jpeg",
    href: "/bbl-forever-young",
  },
  {
    id: "5",
    category: "Skin",
    title: "Botox & Fillers: Redefine Beauty",
    subTitle: "Achieve a Youthful Glow",
    imgUrl: "/img/botox.jpeg",
    href: "/botox-fillers",
  },
  {
    id: "6",
    category: "Skin",
    title: "Agnes RF Microneedling: Poreless Beauty",
    subTitle: "Advanced Skin Treatment",
    imgUrl: "/img/scarlet-srf-min.jpeg",
    href: "/agnes-rf",
  },
  {
    id: "7",
    category: "Skin",
    title: "Skinpen Microneedling: Silky Smooth Skin",
    subTitle: "Revolutionary Skin Therapy",
    imgUrl: "/img/microneedling-min.jpeg",
    href: "/skinpen-microneedling",
  },
  {
    id: "8",
    category: "Skin",
    title: "Skin Care: The Ultimate Regimen",
    subTitle: "Comprehensive Skin Solutions",
    imgUrl: "/img/skinpen-min.jpeg",
    href: "/skin-care",
  },
  {
    id: "9",
    category: "Skin",
    title: "Spider Vein Removal: Unveil Flawless Legs",
    subTitle: "Laser-Powered Vein Therapy",
    imgUrl: "/img/skincare-min.jpeg",
    href: "/spider-vein-removal",
  },
  {
    id: "10",
    category: "Skin",
    title: "Facials: Intense Hydration",
    subTitle: "Luxury Meets Skincare",
    imgUrl: "/img/facials.jpeg",
    href: "/facials",
  },
  {
    id: "11",
    category: "Skin",
    title: "Laser Hair Removal: Be Silky Smooth",
    subTitle: "Permanent Hair Reduction",
    imgUrl: "/img/laser-hair.jpeg",
    href: "/laser-hair-removal",
  },
  {
    id: "12",
    category: "Skin",
    title: "IV Therapy: Replenish Your Body",
    subTitle: "IV Therapy",
    imgUrl: "/img/iv-therapy.jpeg",
    href: "/iv-therapy",
  },
  {
    id: "13",
    category: "Skin",
    title: "Cryo Treatments: Freeze Your Way to Beauty",
    subTitle: "Cryo Treatments",
    imgUrl: "/img/cryo.jpeg",
    href: "/cryo-treatments",
  },
  {
    id: "14",
    category: "Skin",
    title: "Packages: Ultimate Beauty Experience",
    subTitle: "Tailored Skincare Journeys",
    imgUrl: "/img/packages-min.jpeg",
    href: "/packages",
  },
];
